[package]
name = "wp-media-downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
serde_json = "1.0"
futures-util = "0.3"